//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatamanipulatieAnime_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimeModel : DbContext
    {
        public AnimeModel()
            : base("name=AnimeModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_Adaptatie> P_Adaptatie { get; set; }
        public virtual DbSet<P_Aflevering> P_Aflevering { get; set; }
        public virtual DbSet<P_Auteur> P_Auteur { get; set; }
        public virtual DbSet<P_Genre> P_Genre { get; set; }
        public virtual DbSet<P_Genre_Lijst_Manga> P_Genre_Lijst_Manga { get; set; }
        public virtual DbSet<P_Genre_lijstAnime> P_Genre_lijstAnime { get; set; }
        public virtual DbSet<P_Geslacht> P_Geslacht { get; set; }
        public virtual DbSet<P_Manga> P_Manga { get; set; }
        public virtual DbSet<P_Personage> P_Personage { get; set; }
        public virtual DbSet<P_Rol> P_Rol { get; set; }
        public virtual DbSet<P_Seizoen> P_Seizoen { get; set; }
        public virtual DbSet<P_Stemacteur> P_Stemacteur { get; set; }
        public virtual DbSet<P_Studio> P_Studio { get; set; }
        public virtual DbSet<P_Verschijning> P_Verschijning { get; set; }
    }
}
