//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatamanipulatieAnime_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Adaptatie
    {
        public int Adaptatie_id { get; set; }
        public Nullable<int> Manga_id { get; set; }
        public Nullable<int> Seizoen_id { get; set; }
    
        public virtual P_Manga P_Manga { get; set; }
        public virtual P_Seizoen P_Seizoen { get; set; }
    }
}
