//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatamanipulatieAnime_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Genre_lijstAnime
    {
        public int GenreLijst_id { get; set; }
        public Nullable<int> Genre_id { get; set; }
        public Nullable<int> Seizoen_id { get; set; }
    
        public virtual P_Genre P_Genre { get; set; }
        public virtual P_Seizoen P_Seizoen { get; set; }
    }
}
