//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatamanipulatieAnime_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Personage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Personage()
        {
            this.P_Verschijningen = new HashSet<P_Verschijning>();
        }
    
        public int Personage_id { get; set; }
        public string Naam { get; set; }
        public int Stemacteur_id { get; set; }
        public int Geslacht_id { get; set; }
        public string Omschrijving { get; set; }
    
        public virtual P_Geslacht P_Geslacht { get; set; }
        public virtual P_Stemacteur P_Stemacteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Verschijning> P_Verschijningen { get; set; }
    }
}
