//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatamanipulatieAnime_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Verschijning
    {
        public int Verschijning_id { get; set; }
        public int Personage_id { get; set; }
        public int Seizoen_id { get; set; }
        public int Rol_id { get; set; }
    
        public virtual P_Personage P_Personage { get; set; }
        public virtual P_Rol P_Rol { get; set; }
        public virtual P_Seizoen P_Seizoen { get; set; }
    }
}
